#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep "\.py$")
if [ "$files" = "" ]; then
    exit 0
fi

dir=$(git rev-parse --git-dir)/../
pass=true

for file in ${files}; do
    result=$(flake8 --config ${dir}/flake8 ${file})
    if [ "$result" != "" ]; then
        echo "\t\033[31mFlake8 Failed ${file}\033[0m"
        pass=false
    fi
done

if ! $pass; then
    echo "\033[41mCOMMIT FAILED\033[0m"
    exit 1
else
    echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi
